### ISSUE TITLE
Unable to set resultDir from jest.config using reporters option

### ISSUE THREAD

**Issue by kushasahu7** [dkelosky/jest-stare#129]
Using 
{
  "reporters": [
    "default",
    ["<rootDir>/my-custom-reporter.js", {"banana": "yes", "pineapple": "no"}]
  ]
}

as mentioned in https://jestjs.io/docs/en/configuration#reporters-array-modulename-modulename-options  for jest-stare to set resultDir, doesn't work. It sets it to default jest-stare folder.

**Comment by dkelosky** [comment]
Hi @kushasahu7  - currently, jest-stare only supports accepting config via the `jest-stare` field in `package.json`.  I think the configuration passing as you linked above is a fairly new feature of `jest`... this will be an enhancement, and I'll mark it that way.

**Comment by mastrodaro** [comment]
This seems to be great option to dont mess package.json and got all jest related config in one place.

+1

**Comment by dkelosky** [comment]
I've been a bit slow but maybe I'll look to get this in over the next couple of weeks. Thanks for confirming

**Comment by dkelosky** [comment]
this should work in version `jest-stare@1.23.0`

**Comment by kushasahu7** [comment]
Thanks , will test it out soon.
