### ISSUE TITLE
[Suggestion] Custom page title and titlebar headline

### ISSUE THREAD

**Issue by RegisImbellus** [dkelosky/jest-stare#139]
Instead of the page title being "jest-stare!" and the titlebar reading "jest-stare", it'd be ideal to pass variables in from CI, e.g. the repository and branch name.

e.g. 
```
REPORT_TITLE="${REPO} - Unit Test Report"
REPORT_HEADLINE="${REPO}/${BRANCH}"
```

**Comment by dkelosky** [comment]
That's a good idea, open to submitting a PR?
