### ISSUE TITLE
Specifying a resultDir suppresses report link message in logs

### ISSUE THREAD

**Issue by hyperh** [dkelosky/jest-stare#202]
I'm on `"jest-stare": "^1.25.0",`

I would expect to see the following after running my tests:
```
**  jest-stare --reporters: wrote output report to ./jest-stare/index.html	**
jest-html-reporter >> Report generated (./jest/reports/jest-html-reporter.html)
```

This just lets me click the link in the terminal to go to the report rather than dig for it in my file explorer.

However, the `jest-stare` message is suppressed when I do the following:
```
const reporters = [
  'default',
  ['jest-stare', { resultDir: ... }],
  ['jest-html-reporter', {...}]
]
```
If it's just

```
const reporters = [
  'default',
  'jest-stare',
  ['jest-html-reporter', {...}]
]
```

seems to be ok.

**Comment by dkelosky** [comment]
Thanks for reporting.  I'll try it out shortly and see if I get the same result

**Comment by dkelosky** [comment]
I confirmed this is an issue.  I'll look at a fix
