### ISSUE TITLE
Possibility to add file to the test report

### ISSUE THREAD

**Issue by storralba-elsevier** [dkelosky/jest-stare#242]
Hi, I think that a nice improvement would be to be possibility to add and screenshot or any other file (text file ex: test data) to the report.

**Comment by dkelosky** [comment]
I'm pretty open to pull requests if you would like to contribute.  Otherwise, I'll be slow 😀

**Comment by storralba-elsevier** [comment]
I am mostly a user not an expert on JS, but if I have a change I will give it a chance. My main issue is how to expose the reporter.
Thanks in any case.

Sergi Torralba
