### ISSUE TITLE
XML file output

### ISSUE THREAD

**Issue by gbhasha** [dkelosky/jest-stare#247]
Can we have option to output the test results in xml file format, which would be very similar to the output generated in https://github.com/michaelleeallen/jest-junit-reporter.

Some CI/CD tools expects a xml file instead of a json. By having this feature, we could have one single npm module(this one) instead of adding 2 npm dependencies.

**Comment by dkelosky** [comment]
Hi @gbhasha - do you simply need the JSON IN XML format?  For example, transforming JSON keys into XML tags?

Or do you need this in some special JUnit XML format?

Thanks,
Dan
