### ISSUE TITLE
Include Console output?

### ISSUE THREAD

**Issue by l-abels** [dkelosky/jest-stare#264]
Other reporters such as [`jest-html-reporter`](https://github.com/Hargne/jest-html-reporter) have an option to include the console output captured by Jest.  This is a great feature because you can include important debugging info in the report without cluttering your terminal.

Can we have an option to include that info in a collapsable box at the end of each suite?

**Comment by dkelosky** [comment]
Hi,

Can you share a snippet of what this looks like so I can try it out?

I've been slowly getting caught up updating dependencies, now might be an easy time to add your request in. 

Thanks for the feedback!

--
Dan
