### ISSUE TITLE
Show relative path of test file

### ISSUE THREAD

**Issue by senner008** [dkelosky/jest-stare#269]
Is it possible to show the relative path name of the test file in the report?

**Comment by dkelosky** [comment]
Hi @senner008 

Sorry if I'm misunderstanding.  In this example, there is a relative path of a test file - are you looking for something additional?
![image](https://user-images.githubusercontent.com/14940561/78911627-8bd42880-7a54-11ea-8ac6-727b51a03b65.png)

**Comment by senner007** [comment]
Yes, that's what I mean. Where is that setting?

**Comment by dkelosky** [comment]
Sorry for the delay - this should just display on the latest versions.  Here is the `jest-stare` config: https://github.com/dkelosky/jest-stare/blob/master/package.json#L116
