### ISSUE TITLE
Why do you have tag mochawesome in your repo?

### ISSUE THREAD

**Issue by dnikomon** [dkelosky/jest-stare#277]
Should it work? If it works then please can you share an example and which version of mocha etc you used.

**Comment by dkelosky** [comment]
It was only a search convenience.  I loved using mochawsome and initially searched "mochaawsome for jest".  It didn't exist and this was simply an attempt at getting a "similar" project for jest.

**Comment by dnikomon** [comment]
I actually fell in love with mochawesome and tried to look for jest alternatives too. I guess we are moving away from mocha to jest so tool like that would be cool.

**Comment by dkelosky** [comment]
Thanks for the follow-up, closing this.
