### ISSUE TITLE
Collapsible boxes don't open (2.0)

### ISSUE THREAD

**Issue by nprail** [dkelosky/jest-stare#286]
I just updated to 2.0 and found that the new collapsible boxes don't open. In the JS console, I am seeing a `Cannot convert object to primitive value` error whenever I click one of the accordions. 

I looked at the HTML and it looks fine based on Bootstraps docs so I'm not sure why it isn't working 🙂

**Comment by dkelosky** [comment]
Interesting - I'll check if I get that console message shortly.  Which browser are you using?

Thanks

**Comment by nprail** [comment]
Chrome 81.0.4044.122 on Windows 10.

**Comment by dkelosky** [comment]
Sorry for the delay, I should be free to test this tomorrow.

**Comment by dkelosky** [comment]
I was able to reproduce the error - I think I didn't properly bundle / package all new `.js`. and `.css` files in the `2.0.0` package.

I'll try to republish shortly.

**Comment by dkelosky** [comment]
More specifically `jquery.min.js`.

**Comment by dkelosky** [comment]
More details:  `jquery@3.5` has the issue where `jquery@3.4.1` seems to function properly.

**Comment by dkelosky** [comment]
can you re-test with `jest-stare@2.0.1`?  I simply locked the version - hoping that in a future update beyond `jquery@3.5` this will just work.

Thanks,

**Comment by nprail** [comment]
@dkelosky `2.0.1` solves the issue! Thanks!
