### ISSUE TITLE
Creating directory fails

### ISSUE THREAD

**Issue by VitGottwald** [dkelosky/jest-stare#300]
Running `jest --testPathPattern uss/ZoweUSSNode.unit` in ZOWE Explorer fails with

```
  ● Test suite failed to run

    EISDIR: illegal operation on a directory, mkdir '/'

      at Function.mkDirSync (node_modules/jest-stare/lib/utils/IO.js:27:16)
      at Function.mkdirsSync (node_modules/jest-stare/lib/utils/IO.js:35:16)
      at Processor.generateReport (node_modules/jest-stare/lib/processor/Processor.js:73:17)
      at Processor.generate (node_modules/jest-stare/lib/processor/Processor.js:45:14)
      at Function.run (node_modules/jest-stare/lib/processor/Processor.js:29:62)
      at Reporter.onTestResult (node_modules/jest-stare/lib/reporter/Reporter.js:31:35)
```

This is caused by https://github.com/dkelosky/jest-stare/blob/740dde23253f3056ef48bcf8fb1d220a5f097441/src/utils/IO.ts#L73 trying to create a root directory '/' which fails. I suggest using [mkdirp](https://www.npmjs.com/package/mkdirp) package instead of custom implementation.

**Comment by dkelosky** [comment]
Thanks - I'll wait for feedback on [this ](https://github.com/zowe/vscode-extension-for-zowe/issues/774#issuecomment-623857131) before looking into it more.

**Comment by dkelosky** [comment]
I'll close this.  `mkdirsSync` calls https://github.com/dkelosky/jest-stare/blob/740dde23253f3056ef48bcf8fb1d220a5f097441/src/utils/IO.ts#L62 which checks if a file exists before creating it.  If `existsSync` implementation is overwritten, this fails (but `existsSync` cannot be overridden).

**Comment by VitGottwald** [comment]
Thanks you @dkelosky . I wonder what mkdirp does differently that it did not face the problem with existsSync. Anyway, the issue got resolved and we are moving forward. My apologies for causing trouble.

**Comment by dkelosky** [comment]
They catch errors and ignore them :).  

So, you still get the errors, they're just suppressed.  They catch them and ignore them.  I'm not sure I follow their same line of thinking though.
