### ISSUE TITLE
Not Able to generate the snapshots in the report 

### ISSUE THREAD

**Issue by vikasg52** [dkelosky/jest-stare#347]
![image](https://user-images.githubusercontent.com/8328086/94740594-8ff05b80-0390-11eb-81c7-aaf2f07f8589.png)
pkg.json file:
{
  "name": "frisby-automation",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "report": "allure serve"
  },
  "author": "Vikas Garg",
  "license": "ISC",
  "devDependencies": {
    "frisby": "^2.1.3",
    "jasmine-node": "latest",
    "jest-allure": "^0.1.3",
    "jest-html-reporter": "^3.2.0",
    "snapshot-diff": "^0.8.1"
  },
  "jest": {
    "setupFilesAfterEnv": [
      "jest-allure/dist/setup"
    ],
    "reporters": [
      "default",
      [
        "jest-stare",
        {
          "resultDir": "results",
          "reportTitle": "Test Automation",
          "report": true,
          "testResultsProcessor": "./node_modules/jest-starediff2html",
          "reportSummary": true,
          "resultHtml": "TestReport.html",
          "reportHeadline": "Regression Test",
          "coverageLink": "coverage/lcov-report/index.html",
          "jestStareConfigJson": "jest-stare.json",
          "jestGlobalConfigJson": "globalStuff.json"
        }
      ]
    ]
  },
  "dependencies": {
    "allure": "0.0.0",
    "bespoken-jest-stare": "^1.0.19",
    "diff2html": "^3.1.13",
    "jest-junit": "^11.1.0",
    "jest-snapshot": "^26.4.2",
    "jest-stare": "^2.2.0",
    "jest-tesults-reporter": "^1.1.0"
  }
}

**Comment by vikasg52** [comment]
I want to generate the snapshots like this: last donut chart.
![image](https://user-images.githubusercontent.com/8328086/94741479-cf6b7780-0391-11eb-8828-ff94202f8d21.png)

**Comment by vikasg52** [comment]
@dkelosky Could you please help with the issue mentioned above?

**Comment by dkelosky** [comment]
hi @vikasg52 - I think you'll have to add a snapshot test to get that type of chart.  For example:
```typescript
it("should match some snapshot", () => {
  expect({ some: "data"}).toMatchSnapshot();
});
```

Can you give something like that a try?

**Comment by vikasg52** [comment]
Thank you for your reply, Dkelosky.

**Comment by dkelosky** [comment]
No problem, is it ok to close?  Is this working for you now?

**Comment by vikasg52** [comment]
Actually- I tried the approach but anyhow it din't work for me. I am using frisby framework seems like it is not supported with that:
![Uploading image.png…]()

**Comment by dkelosky** [comment]
I can see how the snapshot method is not part of the way `expect` is called in your example.  However, since it's built on jest, it seems that it should work.  Did you try the example I shared verbatim?
