### ISSUE TITLE
i'm not able able to append the result

### ISSUE THREAD

**Issue by avne31** [dkelosky/jest-stare#36]
I have around 10 pack of scripts each having 5-8 scripts in it. I'm triggering through a batch file. so in that, I only able to get the result of the last pack, so it means it overriding the file not appending. so please help me in this so I can able to solve.

**Comment by dkelosky** [comment]
Hello,

The 10 pack of scripts, are these "test suites" and the 5-8 scripts "tests"?

Which version of jest-stare are you using?

How are you indicating to use jest-stare, as a results processor or reporter? 

Thanks,

**Comment by dkelosky** [comment]
Oh, I think I understand.  Everyone you run jest-stare, it overwrites a previous test result?

**Comment by dogboydog** [comment]
Hi,

You could either specify a new file name every time or we could try to do an enhancement  to provide a JSON file to combine results with

**Comment by avne31** [comment]
hi dkelosky

you are correct.it overrides the test result.
if it starts appending the test result then the problem can be solved

**Comment by avne31** [comment]
hi dogboydog,

I don't have a problem if I able to get the result but can you explain more like how we configure in package.json

thanks

**Comment by avne31** [comment]
`{
		"name": "test",
		"jest": {
				"verbose": true,
				"testMatch": [
						"./api/*_spec.js"
				],
				"testResultsProcessor": "./node_modules/jest-stare"
		},
		"jest-stare": {
				"resultDir": "results/jest-stare",
				"additionalResultsProcessors": [
						"jest-html-reporter",
						"jest-junit"
				],
				"log": "true",
				"resultHtml": "main.html",
				"resultJson": "data.json",
				"jestStareConfigJson": "jest-stare-config.json",
				"coverageLink": "../../coverage/lcov-report/index.html"
		}
}`

this is my package.json

**Comment by dkelosky** [comment]
@avne31 , do you know of another reporter or results processor that has the behavior you're seeking?  If so, can you link it? It would help clear up exactly what you're after.

Alternatively, would an option to create separate folders for each test run instead?

Thanks,

**Comment by dogboydog** [comment]
Hi, 

Check out this section of the readme for the full info of how to configure jest-stare: 
https://github.com/dkelosky/jest-stare/blob/master/README.md#config

If separate reports is okay, I'd recommend using this package to set `JEST_STARE_RESULT_DIR` to a different directory each time:  
https://www.npmjs.com/package/cross-env

Then your npm scripts would look like 
```
{ 
  "scripts" : {
       "test1" : "cross-env JEST_STARE_RESULT_DIR=results/test1 jest  test1OptionsHere",
       "test2" : "cross-env JEST_STARE_RESULT_DIR=results/test2 jest  test2OptionsHere",
  } 
} 
```

**Comment by avne31** [comment]
Hi, at present, I have the list of Frisby specs inside a directory and run those specs individually using jest and batch script.

For exp: Runtest.bat have following commands -
`jest create_account_spec.js  --reporters default jest-stare
jest login_account_spec.js  --reporters default jest-stare ` 

Above command create HTML report for login. After next spec execution, the current spec report overrides previous one. My requirement is to append report when each spec execution completed and only one output directory.  

Thanks

**Comment by dogboydog** [comment]
Okay, we would have to enhance jest-stare to allow for combining with previous results then to fit your use case. Thanks for explaining

**Comment by avne31** [comment]
Hi,

these below HTML reporter can append the test result if it is helpful for you then its great.
[1.] (https://www.npmjs.com/package/protractor-jasmine2-html-reporter)
[2.] ( https://github.com/adamgruber/mochawesome-report-generator)

thanks

**Comment by dkelosky** [comment]
Thanks for the reference material. 

I'm curious, if you prepend JEST_STARE_RESULT_DIR to each test run, and set different directories for each, would that work well for you?  You'd have two reports generated from the sample batch file you supplied.

Thanks,

**Comment by dkelosky** [comment]
JEST_STARE_RESULT_DIR=createResults jest create_account_spec.js --reporters default jest-stare
JEST_STARE_RESULT_DIR=loginResults jest login_account_spec.js --reporters default jest-stare

**Comment by avne31** [comment]
hi,

if you add 1 more attribute in **Config** 
like. 
_**--overwrite      boolean      true/false        Overwrite existing report files or not**_

as per the requirement user can use it either(true or false)

thanks

**Comment by avne31** [comment]
hi kelosky,

it's not working for me 
`JEST_STARE_RESULT_DIR=createResults jest create_account_spec.js --reporters default jest-stare
JEST_STARE_RESULT_DIR=loginResults jest login_account_spec.js --reporters default jest-stare`

I want to append all test results into a single file because the batch script triggering jest then jest call `_spec.js` and the process go on. so I want to append each result into a file.

thanks

**Comment by dogboydog** [comment]
We may be able to do the enhancement, but I was wondering why you run these tests separately if you want all one report? Can't you do one script with "jest .*_spec.js" that will run all of your tests at once?

**Comment by avne31** [comment]
Hi,

I can but i have pass different different argument in each scripts
according to situations that's why I'm doing like this.

Thanks

**Comment by dkelosky** [comment]
Thanks for the feedback. 

May try to hack something together soon but am traveling currently.

**Comment by avne31** [comment]
okay

hope for the best.

**Comment by avne31** [comment]
find any way of doing this??

**Comment by dkelosky** [comment]
Yeah, I have a prototype working. But it has problems and only works when
using jest-stare as a results processor.

Will try to update with some details soon.  Still on travel

**Comment by avne31** [comment]
okay thanks

**Comment by dkelosky** [comment]
hi - sorry, its going to be a few days more on this.  i just haven't had time to work on this enhancement with travel.  one note, when merged multiple runs it won't be clear when is the proper time to delete and start over, so  when this enhancement is completed, the report must be manually deleted

**Comment by avne31** [comment]
okay
I will be waiting for it and thanks.

**Comment by dkelosky** [comment]
it'll have some quirks, but if you `npm install jest-stare@next` and set the `jest-stare` config to have:
```
"jest-stare": {
    "merge": "true",
   ...
```

You can see if this is the behavior you were after (if things merge as you expected).

**Comment by avne31** [comment]
I appreciate your work. 

I have observed some issue while using jest-stare@next:
1. if we have 3 scripts and run using jest it appends the log into HTML report but if try to run these scripts in the iteration, it is not appending the previous iteration report. I think naming convention for test result could be an issue. Unique name (test name with timestamp ) could resolve the issue.
2. Test failure and passed count falsy (please refer attachment)
![jest_stare_test_screenshot](https://user-images.githubusercontent.com/38249841/40870939-0828df9a-6650-11e8-9a1d-af6faaad493a.png)

thanks for the support again!

**Comment by dkelosky** [comment]
Point 2 is clear.  That's a quirk - it'll be fairly straightforward to fix the counts.  

For point 1, I'm not sure of the exact use case.  What do you mean by an iteration?  What I've done in this first round, if you run test suites, those are saved in the html report.  If you run again and **new** test suites are detected, only new test suites will be added to the report (old ones are not overwritten).  

Uniqueness is by file path of the test suite.  Is the scenario your after that you run a test suite, add new tests to that test suite and verify the new tests are appended?

**Comment by avne31** [comment]
Hi dkelosky,

My use-case is to run a fixed set of script multiple times into a loop. Here I have to execute create_account_spec and login_account_spec two times using batch script.

**test.bat**
```
for /L %%n in (1,1,2) do @(
  set param={key1:value1}  // using these parameter value into script
  jest create_account_spec.js 

  set param={key2:value2} // using these parameter value into script
  jest login_account_spec.js 
)

```
"param" value would be updated in each iteration. So it could generate different logs after each script execution.

The expected test report path in HTML report is required like:
/apis/create_account_spec_02062018_174950.js
/apis/login_account_spec_02062018_174951.js
/apis/create_account_spec_02062018_174952.js
/apis/login_account_spec_02062018_174953.js

To identify test result(pass/fail) at what time in the iteration, we are expecting test result with the unique path or something else to identify.
So it would basically cover the whole iteration logs.

Thanks

**Comment by dkelosky** [comment]
So initially I assumed you wanted to run tests, add a few tests and see only the new tests added to the report. 

Can't your script generate unique file names upfront and then be run via jest if you must go this route?  

Separate perhaps you can write your name/value pairs to a json file, read that in from your tests, and loop through all values in a single test run?

**Comment by avne31** [comment]
please let me know if you have something for my issue because test cases not appending for the same name while iterating the API.

thanks

**Comment by dkelosky** [comment]
I put this on hold because I'm not sure it makes sense to go down this path.  Appending tests to an HTML file was an interesting idea.  But I think generating unique test names is out of scope.

In your scripts, before running jest, can you read your test suite, get current date and time, append date and time, write this test suite file with date and time in file name,  run jest against that file name, and then delete that file name? 

Using the merge option this should work for you.

I could try to show you what this could look like, but I'll be traveling for a couple more weeks.

**Comment by avne31** [comment]
hi,
you are right in many ways, but please think of my perspective too.

If you can provide us an option in **package.json** like 'appendTimestamp'. And at the time when jest-stare build HTML report using jest test result, you can append the current timestamp(if option 'appendTimestamp' in jest-stare configuration is enabled).

Something like that:
`jest-stare: {   "appendTimestamp": "enabled/disabled" }`

or can give an option in command line if possible

jest mytest_spec.js --appendTimestamp enabled

thanks

**Comment by avne31** [comment]
Hi Dan Kelosky,

is there any update or enhancement regarding my issue. 

thanks

**Comment by dkelosky** [comment]
Sorry, not yet.  I think this is something tackled outside of a
reporter/results processor.  Otherwise, if running multiple reporters,
jest-stare test suite names won't match across reports.

I wanted to put a little script together outside of jest-stare to show how
I thought it could have been done, but I have a full schedule over the next
several weeks.

On Jun 20, 2018 3:04 AM, "avne31" <notifications@github.com> wrote:

Hi Dan Kelosky,

is there any update or enhancement regarding my issue.

thanks

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/dkelosky/jest-stare/issues/36#issuecomment-398646257>,
or mute the thread

**Comment by avne31** [comment]
okay.once you have done with your work please let me know because I'm stuck at that point.

thanks

**Comment by avne31** [comment]
I'm not able to find some other package that fulfills my requirement because I wanted to configure APIs through jest.

**Comment by avne31** [comment]
is there any update regarding this issue??

**Comment by dkelosky** [comment]
No update and I'm too limited in free time to do this kind of update (it's
not a reporter task).  jest-stare simply reports test information.
Generating different test suites, test names would fasly report something
that didn't happen.

Sorry to leave you hanging, but I think this should be closed as n/a based
on what I know about this enhancement request.

On Jul 21, 2018 3:15 AM, "avne31" <notifications@github.com> wrote:

is there any update regarding this issue??

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/dkelosky/jest-stare/issues/36#issuecomment-406776706>,
or mute the thread
