### ISSUE TITLE
Missing trailing slash in resultDir.

### ISSUE THREAD

**Issue by arthwood** [dkelosky/jest-stare#38]
Default `resultDir` results in broken file structure when generating the report:
I think this:

https://github.com/dkelosky/jest-stare/blob/v1.6.0/src/processor/Config.ts#L50
should add trailing slash also for default value:

```typescript
if (config.resultDir == null) {
  config.resultDir = Constants.DEFAULT_RESULTS_DIR;
}

config.resultDir = config.resultDir + "/";
```

The other thing that would be useful is to allow to pass config options in jest config. The following doesn't seem to work:

```javascript
reporters: [
  ['jest-stare', {
    resultDir: 'report'
  }]
];
```

**Comment by dogboydog** [comment]
Thanks for trying it out. We should fix the slash issue. 

For the config, did you know you can pass config via the "jest-stare" field in package.json or through environmental variables? Maybe we could look into enabling config via the jest-stare reporters  field but I was wondering whether that would solve your use case

**Comment by arthwood** [comment]
Thanks for swift response! 
Yes, I'm using it via `package.json` at the moment. Great job on the reporter!

**Comment by dogboydog** [comment]
Can you give an example of what goes wrong with the result directory? I don't think we've seen it and it would be useful for fixing the issue

**Comment by arthwood** [comment]
Sure, if I remove custom `resultDir` from my `package.json`, the following structure is being generated on the project root:

- jest-stare (empty folder)
- jest-starecss (folder with css files)
- jest-starejs (folder with js files)
- jest-stareindex.html
- jest-starejest-results.json

**Comment by dogboydog** [comment]
Just reproduced that, thank you.

**Comment by dkelosky** [comment]
@arthwood , I'm  incompetent, finally fixed this in v1.6.5 if you can test it out.  thanks

**Comment by arthwood** [comment]
@dkelosky I tested it against `1.6.8` (`1.6.5` had installation failure) and looks good! Thanks!

**Comment by dkelosky** [comment]
Thank you
