### ISSUE TITLE
Adding jest-stare causes test runner to loop and run no tests

### ISSUE THREAD

**Issue by billytetrud** [dkelosky/jest-stare#483]
Just tried adding jest-stare to our project and instead of running tests, jest would say "Determining test suites to run..." then tell me there aren't any tests to run, and then keep looping automatically. Trying to ctrl-c out of it doesn't do anything. I'm on windows 10, tried in powershell and normal cmd prompt. It generates files, but they look initialized but not updated - eg jest-results.json has 0s for number of everything, and empty arrays, with `success: false`. I don't see any other output that illuminates what's going on.

**Comment by dkelosky** [comment]
Until I can try the config, do you think this is what you're running into? https://github.com/dkelosky/jest-stare/issues/25#issuecomment-373895886

**Comment by billytetrud** [comment]
Hmm, that doesn't look similar, no. In particular, I wasn't getting any errors like are mentioned in that issue.
