### ISSUE TITLE
Snapshots column present when there were no snapshot tests

### ISSUE THREAD

**Issue by CoderCoco** [dkelosky/jest-stare#51]
When I'm looking at a report and there are no snapshot tests, the results are rendered with no corresponding pie graph for the group. I would think if there were no snapshot tests, then there should be no ui placeholder displayed.

![capture](https://user-images.githubusercontent.com/1407188/50656461-51323500-0f61-11e9-9a58-ecfc1c1e608e.PNG)

**Comment by dkelosky** [comment]
Here's the plan for this one:
![image](https://user-images.githubusercontent.com/14940561/51010577-f41b1e00-1522-11e9-9394-d6e6dc45958e.png)

Let me know if that's good enough!

**Comment by CoderCoco** [comment]
Yep, that's fine. Looks cleaner than having that empty label

**Comment by dkelosky** [comment]
fixed by #54
