### ISSUE TITLE
Skipping all tests results in error display.

### ISSUE THREAD

**Issue by CoderCoco** [dkelosky/jest-stare#52]
When all tests and test suits are skipped, the corresponding output looks like the tests failed:

![capture](https://user-images.githubusercontent.com/1407188/50656622-d74e7b80-0f61-11e9-844f-bf7088c59e64.PNG)

Adding 1 passing test with the rest skipped seems to have solved the problem.

![capture2](https://user-images.githubusercontent.com/1407188/50656662-f51be080-0f61-11e9-8d6d-9b8b05c602e0.PNG)

**Comment by dkelosky** [comment]
I'll try to fix this one this week.  Sorry, I somehow took myself off watching this repo!

**Comment by dkelosky** [comment]
New output will look like this (no red text box):
![image](https://user-images.githubusercontent.com/14940561/51010136-f7150f00-1520-11e9-9ea2-5198c3c154b2.png)

Does that seem better?

**Comment by CoderCoco** [comment]
Looks good to me. Thanks!
