### ISSUE TITLE
`/doc` is default in `.yarnclean`

### ISSUE THREAD

**Issue by timothy-r-koski** [dkelosky/jest-stare#523]
When running `jest-stare` as a reporter I was getting the following error:
```
Error: An error occurred while adding the reporter at path "[...]/node_modules/jest-stare/lib/index.js".Cannot find module './doc/IJestStareConfig'
```
It seems as though the default `.yarnclean` file will remove all `/doc` dir and files when a `yarn clean` is run. Although I was able to fix the issue by removing `doc` from my `.yarnclean` it might make sense to rename directories with required code so users of `yarn` don't think your package is broken.

**Comment by dkelosky** [comment]
Thanks @timothy-r-koski for reporting - it looks like there is more elaboration [here](https://github.com/yarnpkg/yarn/issues/3517#issuecomment-304865754).  eventually i'll hope to get to this
