### ISSUE TITLE
Output test names relative to project root

### ISSUE THREAD

**Issue by CoderCoco** [dkelosky/jest-stare#53]
It would be nice if in the html output, the test file names were relative to the project root. This would remove some clutter in the ui when running from a CI/CD environment.

For Example:

In my jenkins pipeline, jest-stare reports that tests are named like: `/home/jenkins/workspace/ce_create-performance-class-QQJA254Q6QB2QLHTANX2367QN4XUUAEKPDFVBIZLHLOLVMI2VHHA/src/performance/manager/__tests__/PerformanceApiManager.unit.test.ts`

This string could be shortened to: `src/performance/manager/__tests__/PerformanceApiManager.unit.test.ts`

For reference, here's how the former path looks in the UI:

![capture](https://user-images.githubusercontent.com/1407188/50790132-15161180-128c-11e9-8f4b-acbe00e2daff.PNG)

and what it could look like with the changes:

![capture2](https://user-images.githubusercontent.com/1407188/50790188-3d9e0b80-128c-11e9-83c8-c4511115fa10.PNG)

**Comment by CoderCoco** [comment]
Jest already has a variable called `<rootDir>`, this might help you determine the root of the project without adding too much config :smile:

**Comment by dkelosky** [comment]
how about if it only gave you from `__tests__/` onward?  `<rootDir>` captures the full path up to and including everything before `__tests__`.

**Comment by CoderCoco** [comment]
I think that would be fine, but I don't think that you could rely on __tests__ being consistent from project to project. You might want to look to see if tests could be in a folder other than tests first.

https://jestjs.io/docs/en/configuration#testregex-string may somehow allow this scenario.

**Comment by dkelosky** [comment]
my plan is the take the full `testFilePath` and remove `rootDir` from the front.  What's left in your example, is `__tests__` onward.  i'll publish  (and you can tell me if it's dumb :sunglasses: 

fyi - this can only work when you use the project as a `reporter` - it will not work as a `testResultsProcessor` (the latter appears to be on a path to deprecation).
