### ISSUE TITLE
Files with square brackets in filepath can't be expanded

### ISSUE THREAD

**Issue by themagickoala** [dkelosky/jest-stare#536]
Files with square brackets in their name cannot have their test results expanded due to invalid parsing of the CSS selector in the collapse component. This kind of file name is common in Next.js due to the use of dynamic page slugs.

I recommend switching to a deterministic generated id per test file so that the id can be parsed.

**Comment by dkelosky** [comment]
Thanks for reporting, and sorry for the slow response.  I'll occupied on a lot of other projects, but I'll try to get to this

**Comment by themagickoala** [comment]
Nudge for the bot

**Comment by dkelosky** [comment]
Thanks for keeping the issue alive, still struggling to find time to fix this.

**Comment by themagickoala** [comment]
I understand completely, we all have lives! I'll keep nudging for the bot as long as you need me to 🙂.

**Comment by themagickoala** [comment]
Do we need to remove the `no issue activity` label to stop this from auto-closing?
