### ISSUE TITLE
Support visual regression snapshot using jest-image-snapshot

### ISSUE THREAD

**Issue by japboy** [dkelosky/jest-stare#56]
It would be great to check visual regression just like snapshot diff :D

- https://github.com/americanexpress/jest-image-snapshot

**Comment by japboy** [comment]
hi @dkelosky yes thats something i am wondering.

**Comment by dkelosky** [comment]
Ok cool, maybe I'll try to do this on a weekend and let you know.

Thanks

**Comment by dkelosky** [comment]
Still haven't had time to look at this; added help wanted :smile: .  Perhaps in the upcoming weeks or months I'll try (unless there is a PR before then).

**Comment by dkelosky** [comment]
Fix by @mnikkane , published in `jest-stare@1.12.1`
