### ISSUE TITLE
Performance degradation with large amounts of tests.

### ISSUE THREAD

**Issue by CoderCoco** [dkelosky/jest-stare#58]
When opening a report with a large amount of tests, the report takes some time to load and the graphs animations are choppy during the load.

This is a profile of an environment with 157 Test Suites / 746 Tests / 323 Snapshots:

![capture](https://user-images.githubusercontent.com/1407188/52816101-8193e580-306e-11e9-8174-a223afca13f0.PNG)

As shown, it took 12 seconds to load the report.

**Comment by dkelosky** [comment]
I get the same result with a large test input.  Looks like I'll need some lazy loading or something like you suggested.  Im still not clear how this would impact the toggle of pass/failed tests and donut charts.  I also embedded the entire JSON config and other config within the HTML file.  Perhaps this should be external as well.

**Comment by CoderCoco** [comment]
Yeah you could lazy load the json file as well. Basically load data after the page html renders will provide the best user experience. As for the data in the donut charts, you might want to think about using a class on the html element you are toggling (like .passed .failed .skipped), then you could have the JS toggle on that class.

I just got my new computer build setup so I might have some time this weekend to try some enhancements to this. :smile_cat:

**Comment by dkelosky** [comment]
If you do, please let me know.  I could write tests or help out some how.  I spent some time last weekend, but I'm a little stumped.
