### ISSUE TITLE
For initial log statement, JEST_STARE_LOG setting seems to be ignored

### ISSUE THREAD

**Issue by jkelvie** [dkelosky/jest-stare#65]
Regardless of how JEST_STARE_LOG is set, the onRunStart log seems to be printed out:
```
jest-stare will write each completed run to <JEST_STARE_DIRECTORY>
```

It appears to be coming from this line of code:
https://github.com/dkelosky/jest-stare/blob/master/src/reporter/Reporter.ts#L52

An additional statement that comes AFTER jest runs, does seem to be successfully suppressed, so not sure why this one is not.

**Comment by dkelosky** [comment]
Interesting, I thought I had tests to capture this.  What version do you currently have installed?

**Comment by jkelvie** [comment]
1.11.2 - just saw a new version came out 7 days ago - should I try that?

**Comment by dkelosky** [comment]
Nope - the bug occurs in that version :smile: .  I'll see if I can get this fixed over the weekend.  Thanks for reporting

**Comment by jkelvie** [comment]
Hi @dkelosky - I believe this fix was committed to master, and also tagged as version 1.13.1. However, looking at npm, I don't see a release for version 1.13.1 - is there an additional step that is still needed?

**Comment by dkelosky** [comment]
Ah, I forgot to publish! I'll try to do that later today. Sorry for the troubles

**Comment by jkelvie** [comment]
No problem! I love what you have done. Thanks!

**Comment by dkelosky** [comment]
Thanks!  1.13.1 should be published now. 

Take care,
