### ISSUE TITLE
Way to combine assets files

### ISSUE THREAD

**Issue by mifas** [dkelosky/jest-stare#68]
Is there a way to combine assets to a single file. Currently [mochawesome-report-generator](https://github.com/adamgruber/mochawesome-report-generator) has this option

**Comment by dkelosky** [comment]
Are they combined into an archive?  I took a look, but I'm not sure which option you're specifically mentioning.

Thanks,

**Comment by mifas** [comment]
There are combining into one single `.html` file. Please check below option

![image](https://user-images.githubusercontent.com/4384874/53860464-1b223780-401c-11e9-84f5-ed50fef483ba.png)

**Comment by dkelosky** [comment]
I see.  There is no way to do this at the moment.  I'll leave this open as a potential future enhancement.  Thanks!
