### ISSUE TITLE
Display pendong message in report

### ISSUE THREAD

**Issue by DemianTinkiel** [dkelosky/jest-stare#74]
The pending function takes in an optional reason string parameter. Would be nice if when the argument passed, it is displayed in the HTML report

**Comment by dkelosky** [comment]
Good idea.  I hadn't realized this.  Hopefully it would be a pretty straightforward thing to implement.

**Comment by dkelosky** [comment]
pending text is not passed on the results object.  I do not see it on the default reporter either.  I will probably close this soon assuming there is no way to obtain `pending` text.
