### ISSUE TITLE
Image snapshots do not match "Expected image to be the same size as the snapshot.."

### ISSUE THREAD

**Issue by test-pilott** [dkelosky/jest-stare#76]
First of all, thanks for this awesome html reporter!

I get this issue when the image snapshot fails for a different error and this doesn't get picked up by the matcher in jest-stare so the snapshot diff is not copied and rendered.
`Error: Expected image to be the same size as the snapshot (2370x6290), but was different (2370x6330).`

Relevant code line: https://github.com/dkelosky/jest-stare/blob/ac83ee473cfefb5e94a2569b681118372cbf14eb/src/render/diff/ImageSnapshotDifference.ts#L12

It just needs to additionally match against `Expected image to be the same size as the snapshot`.

Thanks.

**Comment by test-pilott** [comment]
Here are the two errors different error messages from jest-image-snapshot https://github.com/americanexpress/jest-image-snapshot/blob/48bc2e4b0a980c0a68a7896612ae9fd1dfd4a644/src/index.js#L63

**Comment by dkelosky** [comment]
thanks @test-pilott - I've never actually use the image diff.  Also, @mnikkane was kind enough to open a PR for this capability in the first place.  

I can try to look at it, but I'll be greatly delayed (weeks) before I could look at fixing this.  Alternatively, you can open a PR for this and beat me to it :smile:

**Comment by test-pilott** [comment]
@dkelosky I have a PR but have no permissions to push the feature branch.  Help?

**Comment by dkelosky** [comment]
Thats great, thank you! I assume you cloned this repo to make your branch.  Instead, please fork the repo, open a branch, push there, and then open the PR.

**Comment by dkelosky** [comment]
fixed by #77 and published @1.13.2, thanks!
