### ISSUE TITLE
Using the jest variable <rootDir> in configuration results in errors.

### ISSUE THREAD

**Issue by CoderCoco** [dkelosky/jest-stare#78]
While configuring jest-stare, I attempted to configure my results directory like so:

```json
"jest-stare": {
  "resultDir": "<rootDir>/__tests__/__results__/jest-stare",
  "coverageLink": "../unit/coverage/lcov-report/index.html"
}
```

This leads to the following error:

`Error: ENOENT: no such file or directory, mkdir '<rootDir>/'`

I believe that this should work in accordance with the jest variable: https://jestjs.io/docs/en/configuration#rootdir-string.

For example, the jest-junit plugin supports this config:

```json
"jest-junit": {
  "output": "<rootDir>/__tests__/__results__/junit/junit.xml"
}
```

**Comment by dkelosky** [comment]
Thanks for reporting!  It's a busy time of the year, so I hope to fix this on a free weekend...

**Comment by dkelosky** [comment]
I don't think you can use `<rootDir>` as described above:
```
"jest-stare": {
  "resultDir": "<rootDir>/__tests__/__results__/jest-stare",
  "coverageLink": "../unit/coverage/lcov-report/index.html"
}
```

It's merely for:

> The root of the directory containing your Jest config file or the package.json or the pwd if no package.json is found

Not quite a variable to be honored by reporters.  Is that your take?

**Comment by CoderCoco** [comment]
Sorry just saw your update, roodDir is a property that you can set in your jest config: https://jestjs.io/docs/en/configuration.html#rootdir-string.

I use it in one of my projects like so.

```json
{
  "collectCoverage": true,
  "collectCoverageFrom": ["src/**/*.ts"],
  "coverageDirectory": "<rootDir>/__tests__/__results__/unit/coverage",
  "coverageReporters": [
    "json",
    "lcov",
    "text",
    "cobertura"
  ],
  "displayName": "Unit",
  "modulePathIgnorePatterns": [
    "__tests__.*/__snapshots__/"
  ],
  "preset": "./__tests__/config/jest.preset.json",
  "rootDir": "../../../",
  "setupFilesAfterEnv": ["<rootDir>/__tests__/config/unit/test-setup.ts"],
  "testPathIgnorePatterns": [
    "/node_modules/",
    "__integration__",
    "<rootDir>/__tests__/__results__"
  ],
  "testRegex": "test\\.(ts|js)"
}
```

with this as the preset.json file

```json
{
  "globals": {
    "ts-jest": {
      "diagnostics": false
    }
  },
  "moduleFileExtensions": ["ts","js"],
  "reporters": ["default", "jest-stare", "jest-junit"],
  "testEnvironment": "node",
  "transform": {
    ".(ts)": "ts-jest"
  }
}
```

**Comment by dkelosky** [comment]
Thanks, I'll look again
