### ISSUE TITLE
Use latest version of diff2html to avoid lodash.merge vuln

### ISSUE THREAD

**Issue by YOU54F** [dkelosky/jest-stare#79]
Hi,

diff2html has just been updated to remove the vulnerable lodash.merge package

released at 2.9.0, is it possible to update jest-stare to use this?

see https://github.com/rtfpessoa/diff2html/issues/216

Thanks

**Comment by dkelosky** [comment]
I hope it would be possible.  Any chance you can submit a PR?  I'll hope to get to recent issues soon, but I am a bit behind on other projects as well. 

Thanks,

**Comment by YOU54F** [comment]
@dkelosky - No worries, yes I would be glad to help, will propose one shortly thanks!

**Comment by YOU54F** [comment]
thanks @dkelosky!

**Comment by dkelosky** [comment]
Thanks for the help
