### ISSUE TITLE
Disabling pie charts on report

### ISSUE THREAD

**Issue by cpandit201** [dkelosky/jest-stare#82]
Is there a way to disable pie charts from generated report using environment variables or any configuration?

![image](https://user-images.githubusercontent.com/42322819/58006564-fbbc8600-7b05-11e9-9f0b-0902f783677e.png)

Thanks,
Chirag Pandit

**Comment by dkelosky** [comment]
Hi Chirag,

No current way yet, but it would be lightweight to implement in a PR.  I'm a bit behind, but I can consider this as a future enhancement (unless someone opens it before me 😀).

**Comment by cpandit201** [comment]
No issues - will wait. Or will try to understand your architecture and do it myself. Thanks
